name: flutter_geolocation_service
description: Flutter plugin for generic location functionality
version: 0.1.0
homepage: https://github.com/cicimen/flutter_geolocation_service

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.cicimen.flutter_geolocation_service
        pluginClass: FlutterGeolocationServicePlugin
      ios:
        pluginClass: FlutterGeolocationServicePlugin
      linux:
        pluginClass: FlutterGeolocationServicePlugin
      macos:
        pluginClass: FlutterGeolocationServicePlugin
      windows:
        pluginClass: FlutterGeolocationServicePluginCApi
      web:
        pluginClass: FlutterGeolocationServiceWeb
        fileName: flutter_geolocation_service_web.dart

